name: Deploy Pages to Pelican

on:
  # Trigger the workflow on push or merged pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nelsonjchen/gh-pages-pelican-action@0.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}